# This rule is not used by the project obs-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to obs.wilaris.de resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: obs-operator
    app.kubernetes.io/managed-by: kustomize
  name: bucket-viewer-role
rules:
- apiGroups:
  - obs.wilaris.de
  resources:
  - buckets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - obs.wilaris.de
  resources:
  - buckets/status
  verbs:
  - get
