---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - obs.wilaris.de
  resources:
  - buckets
  - providerconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - obs.wilaris.de
  resources:
  - buckets/finalizers
  - providerconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - obs.wilaris.de
  resources:
  - buckets/status
  - providerconfigs/status
  verbs:
  - get
  - patch
  - update
